# This is cloudbuild file from help of kodeklod GCP devops project tranning
steps:

# Build container Image
- name: "gcr.io/cloud-builders/docker"
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']

# push container image
- name: "gcr.io/cloud-builders/docker"
  args: ['push','gcr.io/$PROJECT_ID/gcpdevops','.']

# Deploy container image on GKE cluster
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-cental1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod
