apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gcp
    spec:
      containers:
      - image: gcr.io/qwiklabs-gcp-01-c7b88bdef9fd/gcpdevops:latest
        name: gcpdevops
        ports:
        - containerPort: 5000
         env:
          - name: PORT
            value: "5000"
